# Generated by Django 4.0.2 on 2022-02-11 11:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kupac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('lozinka', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proizvodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=60)),
                ('cijena', models.IntegerField(default=0)),
                ('opis', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('slika', models.ImageField(upload_to='uploads/proizvodi/')),
                ('kategorija', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trgovina.kategorija')),
            ],
        ),
        migrations.CreateModel(
            name='Narudzba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.IntegerField(default=1)),
                ('cijena', models.IntegerField()),
                ('adresa', models.CharField(blank=True, default='', max_length=50)),
                ('telefon', models.CharField(blank=True, default='', max_length=50)),
                ('datum', models.DateField(default=datetime.datetime.today)),
                ('status', models.BooleanField(default=False)),
                ('kupac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trgovina.kupac')),
                ('proizvod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trgovina.proizvodi')),
            ],
        ),
    ]
